services:
  app:
    image: juanalves/fhi-app:v1.9

  proxy:
    image: nginx:alpine
    ports:
      - "80:80" 
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/lib/letsencrypt:/var/lib/letsencrypt
